# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a709e5f06e9bf0c22f2b59b3c3ebd68dec7ac4357f134de67a30eb8d6e41e1ca75aed4d7f043a5fc7ffed29886fe3181e263ca0ab06539294227cf0ebd471a

test:
  secret_key_base: 6112a054bd1069ca065e8c5c9132e264a6c84c356641ce3c6e591e9d1057a8cf6bf322d1e81a3fe969a86bba0b4a1560260a612e5a4d4adc0607b6a0a8519d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
